#!/usr/bin/env python3
"""
Generate the seven preview pages.

The chrome (unofficial ribbon, brand bar, the city's nav, the sub-nav across these
previews, footer) is identical on every page, so it lives here. Run `python3 build.py`
and commit the HTML it writes; GitHub Pages serves plain static files.
"""

import io
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Published Pool Relay views. Each is scoped to exactly what its page is about.
EMBED = {
    "hub":       "6EZG0JhwbcBnJQJ0BPuJGD",   # all three indoor pools, Facilities menu
    "moana":     "6FLgbChTvYJ9HIzrOvff6g",   # Moana Springs, Pools menu
    "northwest": "vNTbLJ8djEkrM2EFKiRA5l",   # Northwest Pool, Pools menu
    "emnecc":    "1MJf54cfzT6C58wRnPNk76",   # Evelyn Mount Northeast Community Center
    "lap":       "2xIy3AuLknYSLUIjcYrWRf",   # Lap Swim, Pools menu
    "open":      "78pCfMc1pHs0bJjP7O2Hj7",   # Open Swim, Facilities menu
    "fit":       "qcu3LZLAAL4xRScATCQQrR",   # Water Fitness, Facilities menu
}

NAV = [
    ("index.html",         "Aquatics"),
    ("moana-springs.html", "Moana Springs"),
    ("northwest.html",     "Northwest Pool"),
    ("emnecc.html",        "Evelyn Mount NE"),
    ("lap-swim.html",      "Lap Swim"),
    ("open-swim.html",     "Open Swim"),
    ("water-fitness.html", "Water Fitness"),
]

AQUATICS = "https://www.reno.gov/parks-and-recreation/recreation/aquatics/index.php"
LAP_PDF = "https://www.reno.gov/Documents/Parks%20and%20Recreation/Recreation/Aquatics/2026-2027%20Fall-Spring%20Lap%20Swim%20Schedule.pdf"
OPEN_PDF = "https://www.reno.gov/Documents/Parks%20and%20Recreation/Recreation/Aquatics/2026-2027%20Fall-Spring%20Open%20Swim%20Schedule%208.10.pdf"


def cal(key, title, short=False, caption=""):
    """One live calendar plus its caption line."""
    token = EMBED[key]
    cls = "cal short" if short else "cal"
    tail = f" &nbsp;&mdash;&nbsp; {caption}" if caption else ""
    return f"""  <div class="{cls}">
    <iframe src="https://www.poolrelay.com/embed/{token}"
            title="{title}" loading="lazy"></iframe>
  </div>
  <p class="capt">Live from Pool Relay &middot;
    <a href="https://www.poolrelay.com/v/{token}" target="_blank" rel="noopener">open the full calendar &rarr;</a>{tail}
  </p>
"""


def shell(slug, title, description, body):
    subnav = "\n".join(
        '    <li{on}><a href="{href}">{label}</a></li>'.format(
            on=' class="on"' if href == slug else "", href=href, label=label)
        for href, label in NAV)
    return f"""<!DOCTYPE html>
<!--
  UNOFFICIAL PREVIEW. Not a City of Reno website.
  Generated by build.py — edit that, not this file.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@400;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
</head>
<body>

<div class="ribbon">
  <b>Unofficial preview.</b> Not a City of Reno page. A replica of the
  <a href="{AQUATICS}" target="_blank" rel="noopener">Reno Parks and Recreation aquatics pages</a>
  with live <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool&nbsp;Relay</a> calendars.
</div>

<header class="brandbar">
  <div class="wrap inner">
    <a class="mark" href="index.html"><span class="city">CITY OF RENO</span>Parks and Recreation</a>
    <div class="tel">Moana Springs 775-393-1070 &middot; Northwest 775-334-2203 &middot; EMNECC 775-334-2262</div>
  </div>
</header>

<nav class="main">
  <ul>
    <li class="on"><a href="index.html">Recreation</a></li>
    <li><a href="https://www.reno.gov/parks-and-recreation/" target="_blank" rel="noopener">Adaptive Recreation</a></li>
    <li><a href="https://www.reno.gov/parks-and-recreation/" target="_blank" rel="noopener">Parks &amp; Facilities</a></li>
    <li><a href="https://www.reno.gov/parks-and-recreation/" target="_blank" rel="noopener">Youth &amp; Teens</a></li>
    <li><a href="https://www.reno.gov/parks-and-recreation/" target="_blank" rel="noopener">Resources</a></li>
  </ul>
</nav>

<nav class="sub">
  <ul>
{subnav}
  </ul>
</nav>

{body}
<footer>
  <div class="wrap">
    <p><strong>Unofficial preview.</strong> Built to show what the Reno aquatics pages would look
    like with a live calendar on each one. Not affiliated with the City of Reno.</p>
    <p>Schedules transcribed 23 September 2026 from the city's
    <a href="{LAP_PDF}" target="_blank" rel="noopener">Lap Swim</a> and
    <a href="{OPEN_PDF}" target="_blank" rel="noopener">Open Swim</a> schedules (both effective
    August 10, 2026), the Water Fitness page, each facility's page on reno.gov, and the Notice of Pool Closures. Calendars by
    <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool Relay</a>.</p>
  </div>
</footer>

</body>
</html>
"""


# ── The findings block, shared by the hub and the facility pages ──────────────
QUESTIONS = """<section class="wrap">
  <h2>Questions for the aquatics office</h2>
  <p>Everything here was transcribed from what Reno publishes. These are the places where the
  sources disagree, go quiet, or where we had to make a call &mdash; each one is also written on the
  calendar entry itself.</p>

  <ul class="qa">
    <li>
      <div class="q"><span class="tag clash">Conflict</span>Moana Springs weekend lap swim: which times are right?</div>
      <div class="a">The Lap Swim Schedule PDF and the Moana Springs page disagree three times.
      Saturday's 5&ndash;10-lane block ends at 12:30 in the PDF and 12:00 on the page; Saturday's
      6&ndash;8-lane block starts at 1:00 in the PDF and 12:30 on the page; Sunday's first block ends at
      2:30 in the PDF and 3:00 on the page. The calendar follows the PDF.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>The September 27 swim clinic at Northwest</div>
      <div class="a">The closure notice lists a special event, a swim clinic, with no hours. Which Sunday
      sessions does it replace &mdash; lap swim, open swim, Deep Water Fitness &mdash; and for how long?</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Northwest water fitness: which pool, and from when?</div>
      <div class="a">The Northwest page says water fitness &ldquo;starts September 2026&rdquo; but gives no
      date and names no pool. We put Water Fitness and Deep Water Fitness in the main pool and Shallow
      Water Fitness in the 3-foot training pool, from the first week of September.</div>
    </li>
    <li>
      <div class="q"><span class="tag clash">Conflict</span>Northwest's midday class: 11:30 or 11:45?</div>
      <div class="a">The Water Fitness page starts the Wednesday and Friday midday class at 11:30; the
      Northwest facility page says 11:45 (both agree on 11:45 for Monday). The calendar uses 11:45.</div>
    </li>
    <li>
      <div class="q"><span class="tag ours">Ours</span>Lane ranges shown at their minimum</div>
      <div class="a">The lap schedule gives most blocks as a range, like &ldquo;(8&ndash;10)&rdquo; or
      &ldquo;(2&ndash;10)&rdquo;. The calendar shows the lanes that are always open. When do the others
      open to lap swim? Say, and the calendar shows each extra lane at the hour it opens.</div>
    </li>
    <li>
      <div class="q"><span class="tag ours">Ours</span>Which Moana lanes do the competition-pool classes use?</div>
      <div class="a">Water Walking and Water Fit name the competition pool but not the lanes. We put them
      on lanes 16&ndash;19, away from lap swim.</div>
    </li>
    <li>
      <div class="q"><span class="tag clash">Conflict</span>Evelyn Mount Northeast: 130 or 1301 Valley Road?</div>
      <div class="a">The Lap Swim Schedule PDF gives &ldquo;130 Valley Rd.&rdquo;; the Open Swim PDF and the
      facility page give 1301. Probably a typo in the lap PDF.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>What day in June does the fall&ndash;spring schedule end?</div>
      <div class="a">Each facility page gives &ldquo;August 10, 2026 &ndash; June 2027&rdquo;. With a date,
      the calendar ends the season on it and the summer schedule can go in beside it now.</div>
    </li>
  </ul>
</section>

"""

FEES = """  <h2 style="margin-top:34px">Drop-in rates</h2>
  <div class="scroller">
  <table class="sched">
    <thead><tr><th>Labor Day &ndash; Memorial Day</th><th>Child (0&ndash;2)</th><th>Youth (3&ndash;17)</th><th>Adult (18&ndash;59)</th><th>Senior (60+)</th></tr></thead>
    <tbody>
      <tr><td>Open swim and full facility</td><td class="n">$0</td><td class="n">$7</td><td class="n">$10</td><td class="n">$8</td></tr>
      <tr><td>Water Fitness / Aqua Joints</td><td class="n">&mdash;</td><td class="n">&mdash;</td><td class="n">$6.50</td><td class="n">$5.00</td></tr>
    </tbody>
  </table>
  </div>
  <p class="capt">Community Discount Days: Wednesdays and Sundays, open swim only.</p>
"""


# ══ 1. The hub ════════════════════════════════════════════════════════════════
HUB = f"""<section class="wrap hero">
  <div class="crumb">Home &raquo; Parks and Recreation &raquo; Recreation &raquo; Aquatics</div>
  <h1>Aquatics</h1>
  <p class="kicker">Three indoor pools &middot; one calendar &middot; closures included</p>
  <p class="lead">Lap swim, open swim and water fitness at Moana Springs, Northwest Pool and the Evelyn
  Mount Northeast Community Center. Use the <strong>Facilities</strong> menu to narrow to one pool, or
  leave it on <strong>All</strong>.</p>

{cal("hub", "Reno Aquatics — all three indoor pools, this week",
     caption="Every block shows its pool and how many lanes it takes. Closures appear on the day they happen.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>The schedule and the closures, in one place</h2>
    <p class="q">&ldquo;Can I swim laps at Northwest on Tuesday, October 6?&rdquo;</p>
    <p>The Lap Swim Schedule says yes: Tuesday, 7:00&ndash;8:45am, 7&ndash;8 lanes. The Notice of Pool
    Closures, further down the page, says Northwest is closed that day for a planned power outage. Both
    are right, and a swimmer has to read both.</p>
    <p class="answer">On the calendar, October 6 at Northwest simply shows <b>closed</b>, with Moana
    Springs and Evelyn Mount Northeast open beside it. The same goes for the September 23&ndash;25
    repair and the September 27 swim clinic.</p>
  </div>
</div>

<section class="wrap">
  <h2>The pools</h2>
  <div class="facts">
    <div><b>Moana Springs</b>Competition pool (10 &times; 50 m or 19 &times; 25 yd lanes, 1 m and 3 m
    boards), multi-use pool with slide and lazy river, outdoor soaking pool. 240 W Moana Ln.</div>
    <div><b>Northwest Pool</b>Main pool, 8 &times; 25 yd lanes, 10 ft deep; training pool, 30 &times; 60 ft,
    3 ft deep. 2925 Apollo Way.</div>
    <div><b>Evelyn Mount Northeast</b>4 &times; 25 yd lanes, 5 ft deep, heated to about 86&deg;.
    1301 Valley Rd.</div>
    <div><b>Idlewild and Traner</b>Seasonal outdoor pools. Idlewild's last day this year was
    Labor Day.</div>
  </div>
{FEES}
</section>

{QUESTIONS}"""


def facility(crumb, h1, kicker, lead, key, cal_title, caption, trail_h2, trail_p, answer, extra=""):
    return f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; {crumb}</div>
  <h1>{h1}</h1>
  <p class="kicker">{kicker}</p>
  <p class="lead">{lead}</p>

{cal(key, cal_title, caption=caption)}
</section>

<div class="trail">
  <div class="wrap">
    <h2>{trail_h2}</h2>
    <p>{trail_p}</p>
    <p class="answer">{answer}</p>
  </div>
</div>
{extra}
{QUESTIONS}"""


MOANA = facility(
    "Moana Springs", "Moana Springs Community Aquatics and Fitness Center",
    "Competition pool &middot; multi-use pool &middot; outdoor soaking pool",
    "A 50-meter competition pool with diving boards, a multi-use pool with a slide, lazy river and "
    "splash features, and an outdoor soaking pool in the high 90s. 240 W Moana Ln &middot; 775-393-1070.",
    "moana", "Moana Springs — this week",
    "Use the <strong>Pools</strong> menu to switch between the competition, multi-use and soaking pools.",
    "Two pool layouts, one week",
    "The competition pool runs 25-yard lanes most of the week and 50-meter lanes on Friday mornings, "
    "then goes back to 25 yards for the evening. The lap schedule says so line by line; the facility "
    "page says it again with three different times.",
    "The calendar knows which layout each block uses, so <b>Friday 5:30am reads as 50 meters and Friday "
    "4pm as 25 yards</b>, and a change to either time is made once, in one place.")

NORTHWEST = facility(
    "Northwest Pool", "Northwest Pool",
    "Main pool &middot; training pool &middot; water fitness from September",
    "An 8-lane, 25-yard main pool and a 3-foot training pool with zero-depth entry. "
    "2925 Apollo Way &middot; 775-334-2203.",
    "northwest", "Northwest Pool — this week",
    "Use the <strong>Pools</strong> menu to switch between the main and training pools.",
    "Closures on the day they happen",
    "Northwest has three notices this fall: closed September 23&ndash;25 for a maintenance repair, a swim "
    "clinic on Sunday, September 27, and closed October 6 for a planned NV Energy power outage. They "
    "live in a table on the aquatics page, apart from the schedules they change.",
    "Page to any of those days and the calendar shows it: <b>the closure in place of the sessions it "
    "cancels</b>, and every other day exactly as the schedule reads.")

EMNECC = facility(
    "Evelyn Mount Northeast", "Evelyn Mount Northeast Community Center Pool",
    "Four warm-water lanes &middot; 86&deg; &middot; 5 ft deep",
    "A 4-lane, 25-yard pool heated to about 86 degrees, with lap swim, water fitness, Aqua Joints and "
    "Saturday open swim. 1301 Valley Rd &middot; 775-334-2262.",
    "emnecc", "Evelyn Mount Northeast Community Center pool — this week", "",
    "Why Saturday says &ldquo;2&ndash;4 lanes&rdquo;",
    "Saturday lap swim is 11:30&ndash;2:30 on &ldquo;(2&ndash;4)&rdquo; lanes. The open swim schedule, a "
    "separate PDF, starts open swim at 12:45. Put together, the range explains itself: all four lanes "
    "until 12:45, then two while open swim has the other half.",
    "On the calendar Saturday reads that way: <b>four lanes, then two lanes beside open swim</b>, so "
    "nobody arrives at 1:00 expecting four.")

LAP = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; Lap Swim</div>
  <h1>Lap Swim</h1>
  <p class="kicker">Three pools &middot; 42 lap swim blocks a week &middot; lane counts on every block</p>
  <p class="lead">Lap swim at Moana Springs, Northwest Pool and Evelyn Mount Northeast, with the number of
  lanes and the course for each block.</p>

{cal("lap", "Reno Lap Swim — every pool",
     caption="Use the <strong>Pools</strong> menu to show one pool, or leave it on <strong>All</strong>.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>Tuesday at 7:15am</h2>
    <p>Three tables in the lap schedule, one per pool, each with its own day groupings: &ldquo;Monday -
    Thursday&rdquo; at Moana, &ldquo;Monday - Friday&rdquo; at Northwest, &ldquo;Tuesday and Thursday&rdquo; at
    Evelyn Mount.</p>
    <p class="answer">On the calendar, Tuesday at 7:15 is one look: <b>8 lanes at Moana, 7 at Northwest,
    4 at Evelyn Mount</b> &mdash; nineteen lanes of lap swim across the city.</p>
  </div>
</div>

{QUESTIONS}"""

OPEN = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; Open Swim</div>
  <h1>Open Swim</h1>
  <p class="kicker">Slides, lazy river, diving boards, tot pools</p>
  <p class="lead">Recreational swim at all three indoor pools: the multi-use pool and diving boards at
  Moana Springs, the main and tot pools at Northwest, and Saturday open swim at Evelyn Mount Northeast.</p>

{cal("open", "Reno Open Swim — every pool",
     caption="Use the <strong>Facilities</strong> menu to show one pool.")}
</section>

<section class="wrap">
{FEES}
</section>

"""

FITNESS = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; Water Fitness</div>
  <h1>Water Fitness</h1>
  <p class="kicker">35 classes a week &middot; three pools</p>
  <p class="lead">Water Fitness, Deep and Shallow Water Fitness, Water Walking, Water Fit and Aqua Joints at
  Moana Springs, Northwest Pool and Evelyn Mount Northeast. No swimming skills needed; adults 18+.
  $6.50 drop-in; $5.00 for seniors.</p>

{cal("fit", "Reno Water Fitness — every class",
     caption="Use the <strong>Facilities</strong> menu to show one pool.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>One schedule, kept in two places</h2>
    <p>The classes are listed twice: in a table per pool on the Water Fitness page, and again in each
    facility's &ldquo;Expand Details&rdquo; panel. The two agree everywhere but one class &mdash;
    Northwest's midday Wednesday and Friday session starts at 11:30 on one and 11:45 on the other.</p>
    <p class="answer">On the calendar each class exists once, <b>so the time a swimmer reads is the time
    that was entered</b>, whichever page they came from.</p>
  </div>
</div>

"""

PAGES = [
    ("index.html", "Aquatics &mdash; City of Reno (Pool Relay preview)",
     "Unofficial preview of the Reno aquatics page with one live Pool Relay calendar for all three indoor pools.", HUB),
    ("moana-springs.html", "Moana Springs &mdash; City of Reno (Pool Relay preview)",
     "Unofficial preview: Moana Springs with a live calendar for all three pools.", MOANA),
    ("northwest.html", "Northwest Pool &mdash; City of Reno (Pool Relay preview)",
     "Unofficial preview: Northwest Pool, with its closures on the calendar.", NORTHWEST),
    ("emnecc.html", "Evelyn Mount Northeast Community Center Pool &mdash; City of Reno (Pool Relay preview)",
     "Unofficial preview: the Evelyn Mount Northeast Community Center pool.", EMNECC),
    ("lap-swim.html", "Lap Swim &mdash; City of Reno (Pool Relay preview)",
     "Unofficial preview: lap swim at all three Reno indoor pools on one calendar.", LAP),
    ("open-swim.html", "Open Swim &mdash; City of Reno (Pool Relay preview)",
     "Unofficial preview: open swim at all three Reno indoor pools.", OPEN),
    ("water-fitness.html", "Water Fitness &mdash; City of Reno (Pool Relay preview)",
     "Unofficial preview: every Reno water fitness class on one calendar.", FITNESS),
]

if __name__ == "__main__":
    for slug, title, description, body in PAGES:
        html = shell(slug, title, description, body)
        with io.open(os.path.join(HERE, slug), "w", encoding="utf-8") as f:
            f.write(html)
        print(f"wrote {slug} ({len(html.encode()):,} bytes)")
